# DevOps-Practicum

Добрый день!

Вашему вниманию мое описание тестового задания.

### 1. Локальный запуск

Для локального запуска Flask-приложения использовался инструмент для создания 
изолированной среды python - **virtualenv**. После создания виртуального окружения 
и загрузки всех необходимых зависимостей из файла _requirements.txt_ был произведен запуск
приложения, в процессе которого была возвращена ошибка связанная с модулем WTForms: 

`_AttributeError: module 'wtforms.validators' has no attribute 'required_`

Согласно документации WTForms https://wtforms.readthedocs.io/en/stable/changes/#version-1-0-2
в версии 1.0.2 (Released 2012-08-24)

`* Distinguish Required validator into InputRequired and DataRequired.`

Так как в файле зависимостей _requirements.txt_ не были указаны версии, то менеджер пакетов установил самый
актуальный WTForms 3.0.1, в котором изменены вызовы валидатора.

![2.png](screens%2F2.png)

Если изменить "устаревший" вызов валидатора формы: `required` --> `DataRequired` (./scripts/**forms.py**),то 
ошибка будет устранена и приложение запустится. Поэтому при использовании **последней актуальной версии** модуля
необходимо провести рефакторинг кода с учетом обновленной документации.

![1.png](screens%2F1.png)

Приложение также можно запустить не меняя вызовы валидаторов в коде. Для этого нужно сменить интерпретатор 
Python 3 на Python 2, обязательно указав в файле зависимостей устаревший _WTForms==1.0.1._

![3.png](screens%2F3.png)

### 2. Упаковка и запуск приложения в Docker.
Для интереса решил попробовать воспользоваться практикой создания многоэтапных сборок
с виртуальным окружением. Понимаю, что использование виртуального окружения внутри изолируемого образа здесь
немного лишняя процедура, но в процессе сборки я пришел к этому решению вот по какой причине. Дело в том,
что во время сборки я получал предупреждение.

`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour 
with the system package manager. It is recommended to use a virtual environment instead`

После усиленных поисков на всевозможных форумах, по поводу этого предупреждения, мною было принято
последовать рекомендациям и найти более 
правильное и безопасное решение. 

Образ собирал с уже исправленным вызовом валидатора в файле **forms.py**

![4.png](screens%2F4.png)

### 3. Запуск приложениче через Docker-compose.

![5.png](screens%2F5.png)

Буду рад попасть к Вам на обучение!



